booster_tracker/urls.py
# booster_tracker/urls.py
from django.urls import path, include  # Add 'include' here
from django.contrib import admin  # Add this for admin.site.urls
from . import views
from booster_tracker.api_views import (
    LaunchOnlyApiView,
    LaunchApiView,
    RocketApiView,
    RocketFamilyApiView,
    OperatorApiView,
    OrbitApiView,
    PadApiView,
    PadInformationApiView,
    LandingZoneApiView,
    LandingZoneInformationApiView,
    StageAndRecoveryApiView,
    LaunchInformationApiView,
    LaunchInformation2ApiView,
    StageApiView,
    StageInformationApiView,
    SpacecraftApiView,
    SpacecraftInformationApiView,
    BoatApiView,
    SpacecraftFamilyApiView,
    HomeDataApiView,
    RocketFamilyInformationApiView,
    SpacecraftFamilyInformationApiView,
    FilteredLaunchDaysApiView,
    EDAApiView,
    AdditionalGraphsApiView,
)

app_name = "booster_tracker"
urlpatterns = [
    # API Endpoints
    path("homedata/", HomeDataApiView.as_view(), name="home"),
    path("launchesonly/", LaunchOnlyApiView.as_view(), name="launches_only"),
    path("launches/", LaunchApiView.as_view(), name="launches"),
    path("stages/", StageApiView.as_view(), name="stages"),
    path("stageinformation/", StageInformationApiView.as_view(), name="stage_information"),
    path("spacecraft/", SpacecraftApiView.as_view(), name="spacecraft"),
    path("spacecraftfamilies/", SpacecraftFamilyApiView.as_view(), name="spacecraft_families"),
    path("spacecraftinformation/", SpacecraftInformationApiView.as_view(), name="spacecraft_information"),
    path("launchinfo/", LaunchInformationApiView.as_view(), name="launch_information"),
    path("launch/", LaunchInformation2ApiView.as_view(), name="new_launch_information"),
    path("rockets/", RocketApiView.as_view(), name="rockets"),
    path("rocketfamilies/", RocketFamilyApiView.as_view(), name="rocket_families"),
    path("familyinformation/", RocketFamilyInformationApiView.as_view(), name="rocket_family_information"),
    path(
        "spacecraftfamilyinformation/",
        SpacecraftFamilyInformationApiView.as_view(),
        name="spacecraft_family_information",
    ),
    path("operators/", OperatorApiView.as_view(), name="operators"),
    path("orbit/", OrbitApiView.as_view(), name="orbit"),
    path("pads/", PadApiView.as_view(), name="pads"),
    path("padinformation/", PadInformationApiView.as_view(), name="pad_information"),
    path("boats/", BoatApiView.as_view(), name="boats"),
    path("landingzones/", LandingZoneApiView.as_view(), name="landing_zones"),
    path("landingzoneinformation/", LandingZoneInformationApiView.as_view(), name="landing_zone_information"),
    path("stageandrecoveries/", StageAndRecoveryApiView.as_view(), name="stage_and_recoveries"),
    path("calendarstats/", FilteredLaunchDaysApiView.as_view(), name="filter_calendar_stats"),
    path("edatable/", EDAApiView.as_view(), name="EDA table"),
    path("additional-graph-info/", AdditionalGraphsApiView.as_view(), name="additional graphs"),
]

# Optional: Add admin URLs if needed (though typically in root urls.py)
if app_name == "booster_tracker":
    urlpatterns += [
        path("admin/", admin.site.urls),  # Add admin if needed for this app
    ]

launches_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from booster_tracker import views
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url="/admin/", permanent=True)),
    path("api/", include("booster_tracker.urls")),
    path("health/", views.health, name="health"),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.TESTING and settings.DEBUG:
    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
        *urlpatterns,
    ]

booster_tracker/models.py
from django.db import models
from booster_tracker.utils import (
    make_ordinal,
    concatenated_list,
    TurnaroundObjects,
    success,
    convert_seconds,
    format_time,
    is_significant,
    get_random_stat,
    process_stat,
)
from datetime import datetime
from django.db.models import Q, Max
from colorfield.fields import ColorField
import pytz
from timezone_field import TimeZoneField

# Choices for fields
RECOVERY_METHODS = [
    ("EXPENDED", "expended"),
    ("OCEAN_SURFACE", "ocean"),
    ("DRONE_SHIP", "ASDS"),
    ("GROUND_PAD", "landing zone"),
    ("PARACHUTE", "parachute"),
    ("CATCH", "catch"),
]
LAUNCH_OUTCOMES = [
    ("SUCCESS", "success"),
    ("FAILURE", "failure"),
    ("PARTIAL FAILURE", "partial failure"),
    ("TBD", "TBD"),
]
LANDING_METHOD_OUTCOMES = [("SUCCESS", "success"), ("FAILURE", "failure"), ("PRECLUDED", "precluded"), ("TBD", "TBD")]
BOAT_TYPES = [
    ("TUG", "tug"),
    ("FAIRING_RECOVERY", "fairing recovery"),
    ("SUPPORT", "support"),
    ("SPACECRAFT_RECOVERY", "spacecraft recovery"),
]
STAGE_TYPES = [("BOOSTER", "booster"), ("SECOND_STAGE", "second stage")]
SPACECRAFT_TYPES = [("CARGO", "cargo"), ("CREW", "crew")]
STAGE_LIFE_OPTIONS = [
    ("ACTIVE", "active"),
    ("RETIRED", "retired"),
    ("EXPENDED", "expended"),
    ("LOST", "lost"),
]
LIFE_OPTIONS = [("ACTIVE", "active"), ("RETIRED", "retired")]
BOOSTER_TYPES = [
    ("MY", "MY"),
    ("PY", "PY"),
    ("CENTER", "center"),
    ("SINGLE_CORE", "single core"),
]

# Create models:


class Operator(models.Model):
    name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to="operator_photos/", default="stage_photos/default_booster.jpg")
    credit = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.name


class RocketFamily(models.Model):
    name = models.CharField(max_length=100, unique=True)
    provider = models.ForeignKey(Operator, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Rocket Families"


class Rocket(models.Model):
    name = models.CharField(max_length=100, unique=True)
    family = models.ForeignKey(RocketFamily, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=LIFE_OPTIONS, default="ACTIVE")
    image = models.ImageField(upload_to="rocket_photos/", default="stage_photos/default_booster.jpg")
    credit = models.CharField(max_length=100, null=True, blank=True)
    color = ColorField(default="#218243")

    def __str__(self):
        return self.name

    @property
    def num_launches(self) -> int:
        """Returns number of times rocket has launched up to current time as an int; excludes precluded launches"""
        return Launch.objects.filter(rocket=self, time__lte=datetime.now(pytz.utc), launch_precluded=False).count()

    @property
    def num_successes(self) -> int:
        """Returns number of times rocket has launched successfully up to current time as an int"""
        return Launch.objects.filter(rocket=self, launch_outcome="SUCCESS", time__lte=datetime.now(pytz.utc)).count()


class Stage(models.Model):
    name = models.CharField(max_length=50)
    rocket = models.ForeignKey(Rocket, on_delete=models.CASCADE)
    version = models.CharField(max_length=20)
    type = models.CharField(max_length=20, choices=STAGE_TYPES)
    image = models.ImageField(upload_to="stage_photos/", default="stage_photos/default_booster.jpg")
    credit = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(max_length=20, choices=STAGE_LIFE_OPTIONS, default="ACTIVE")

    def __str__(self):
        return self.name

    class Meta:
        constraints = [models.UniqueConstraint(fields=["name", "rocket"], name="unique_rocket_stage")]

    @property
    def num_launches(self) -> int:
        """Returns number of times a stage has flown up to current time as an int"""
        return StageAndRecovery.objects.filter(launch__time__lte=datetime.now(pytz.utc), stage=self).count()

    @property
    def fastest_turnaround(self) -> int:
        """Returns the fastest turnaround of the stage to date; returns turnaround in total seconds"""
        if (
            stageandrecovery := StageAndRecovery.objects.filter(stage=self, launch__time__lte=datetime.now(pytz.utc))
            .order_by("stage_turnaround")
            .first()
        ):
            return stageandrecovery.stage_turnaround
        return None


class SpacecraftFamily(models.Model):
    name = models.CharField(max_length=200, unique=True)
    provider = models.ForeignKey(Operator, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=200, choices=LIFE_OPTIONS)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Spacecraft Families"


class Spacecraft(models.Model):
    name = models.CharField(max_length=20)
    nickname = models.CharField(max_length=20, blank=True, null=True)
    version = models.CharField(max_length=20, blank=True, null=True)
    type = models.CharField(max_length=20, choices=SPACECRAFT_TYPES)
    family = models.ForeignKey(SpacecraftFamily, on_delete=models.CASCADE, blank=True, null=True)
    status = models.CharField(max_length=50, choices=STAGE_LIFE_OPTIONS, default="ACTIVE")
    image = models.ImageField(upload_to="spacecraft_photos/", default="spacecraft_photos/default_dragon.jpg")
    credit = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        constraints = [models.UniqueConstraint(fields=["name", "family"], name="unique_family_name")]

    @property
    def num_launches(self) -> int:
        """Returns number of times a spacecraft has flown up to current time as an int"""
        return SpacecraftOnLaunch.objects.filter(launch__time__lte=datetime.now(pytz.utc), spacecraft=self).count()

    @property
    def fastest_turnaround(self) -> int:
        """Returns the fastest turnaround of the spacecraft to date; returns turnaround in total seconds"""
        if (
            spacecraftonlaunch := SpacecraftOnLaunch.objects.filter(
                launch__time__lte=datetime.now(pytz.utc), spacecraft=self
            )
            .order_by("spacecraft_turnaround")
            .first()
        ):
            return spacecraftonlaunch.spacecraft_turnaround
        return None


class Boat(models.Model):
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=200, choices=BOAT_TYPES)
    status = models.CharField(max_length=50, choices=LIFE_OPTIONS, default="ACTIVE")

    def __str__(self):
        return self.name

    class Meta:
        constraints = [models.UniqueConstraint(fields=["name", "type"], name="unique_boat_name_type")]


class Orbit(models.Model):
    name = models.CharField(max_length=200, unique=True)
    nickname = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return self.name


class Pad(models.Model):
    name = models.CharField(max_length=200, unique=True)
    nickname = models.CharField(max_length=25)
    location = models.CharField(max_length=100, null=True, blank=True)
    time_zone = TimeZoneField(use_pytz=True, choices_display="WITH_GMT_OFFSET")
    status = models.CharField(max_length=20, choices=LIFE_OPTIONS, default="ACTIVE")
    image = models.ImageField(upload_to="pad_photos/", default="media/pad_photos/default.png")
    credit = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.nickname

    @property
    def num_launches(self) -> int:
        """Returns number of launches from a pad up to current time as an int"""
        return Launch.objects.filter(pad=self, time__lte=datetime.now(pytz.utc), launch_precluded=False).count()

    @property
    def fastest_turnaround(self) -> int:
        """Returns the fastest turnaround of the stage to date; returns turnaround in total seconds"""
        if (
            launch := Launch.objects.filter(pad=self, time__lte=datetime.now(pytz.utc))
            .order_by("pad_turnaround")
            .first()
        ):
            return launch.pad_turnaround
        return None


class Launch(models.Model):
    time = models.DateTimeField("Launch Time")
    pad = models.ForeignKey(Pad, on_delete=models.CASCADE)
    rocket = models.ForeignKey(Rocket, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, unique=True)
    orbit = models.ForeignKey(Orbit, on_delete=models.CASCADE, null=True, blank=True)
    mass = models.IntegerField(blank=True, null=True, verbose_name="Mass (kg)")
    customer = models.CharField(max_length=200)
    launch_outcome = models.CharField(max_length=200, choices=LAUNCH_OUTCOMES, default="TBD")
    exclude_from_missions = models.BooleanField(
        default=False, help_text="Exclude from mission number (Ex: Starship test missions)"
    )
    launch_precluded = models.BooleanField(default=False, help_text="Exclude from launch number (Ex: AMOS-6)")
    pad_turnaround = models.IntegerField(blank=True, null=True, editable=False)
    company_turnaround = models.IntegerField(blank=True, null=True, editable=False)
    image = models.CharField(max_length=200, blank=True, null=True, editable=False)
    stages_string = models.CharField(max_length=500, blank=True, null=True, editable=False)
    celery_task_id = models.CharField(max_length=255, null=True, blank=True, editable=False)
    x_post_sent = models.BooleanField(default=False, editable=False)
    nxsf_id = models.IntegerField(blank=True, null=True)  # NxSF Launch ID

    class Meta:
        verbose_name_plural = "Launches"
        ordering = ["-time"]

    def __str__(self):
        return self.name

    # Values to ensure infinite loop is not created from signals file
    _from_task = False
    _is_updating_scheduled_post = False

    @property
    def get_image(self) -> str:

booster_tracker/views.py
from django.shortcuts import HttpResponse


def health(request):
    return HttpResponse("Success", status=200)

booster_tracker/templates/base_generic.html
<!-- base_generic.html -->

{% load static %}
<style>
    .nav-icon {
        content: url('{% static "booster-tracker.png" %}');
    }

    @media (max-width: 850px) {
        .nav-icon {
            content: url('{% static "booster-trackertext.png" %}');
        }
    }
</style>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %} {% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon/favicon.ico' %}"/>
        {% block extra_css %}{% endblock %}
    </head>
    <body>
        <nav class="navbar">
            <div class="navbar-container">
                <a href="{% url 'booster_tracker:home' %}" style="-webkit-tap-highlight-color: transparent;">
                    <img alt="Logo" class="logo nav-icon">
                </a>
                <input type="checkbox" id="menu-toggle">
                <div class="hamburger-lines">
                    <span class="line line1"></span>
                    <span class="line line2"></span>
                    <span class="line line3"></span>
                </div>
                <div class="nav-items-wrapper">
                    <ul class="menu-items">
                        <li class="mobile-menu"><a href="{% url 'booster_tracker:home' %}" class="{% if request.path == '/' %}active{% endif %}">Home</a></li>
                        <li><a href="{% url 'booster_tracker:stages' rocket_family_name='falcon' stage_type='booster' %}" class="{% if request.path == '/falcon/booster/' %}active{% endif %}">Boosters</a></li>
                        <li><a href="{% url 'booster_tracker:dragons' %}" class="{% if request.path == '/dragons/' %}active{% endif %}">Dragons</a></li>
                        <li><a href="{% url 'booster_tracker:starship' %}" class="{% if request.path == '/starship/' %}active{% endif %}">Starship</a></li>
                        <li><a href="{% url 'booster_tracker:launches' %}" class="{% if request.path == '/launches/' %}active{% endif %}">Launches</a></li>
                    </ul>
                </div>
                <div class="social-media">
                    <a href="https://x.com/boostertracker" target="_blank">
                        <img src="{% static 'images/x-logo-white.png' %}" style="height: 18px; width:18px;" alt="X" />
                    </a>
                </div>
            </div>
        </nav>
    </body>
</html>

{% block content %}
{% endblock %}

</body>
<!--
    .................../ JS Code for smooth scrolling /...................... -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        // Add smooth scrolling to all links
        $("a").on("click", function (event) {
            // Make sure this.hash has a value before overriding default behavior
            if (this.hash !== "") {
                // Prevent default anchor click behavior
                event.preventDefault();

                // Store hash
                var hash = this.hash;

                // Using jQuery's animate() method to add smooth page scroll
                // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
                $("html, body").animate(
                    {
                        scrollTop: $(hash).offset().top,
                    },
                    800,
                    function () {
                        // Add hash (#) to URL when done scrolling (default click behavior)
                        window.location.hash = hash;
                    }
                );
            } // End if
        });
    });
</script>
</html>